// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbCmt8p5zBZYP5SoDd8uBO7GcEFSu19Ik',
    appId: '1:956367172035:web:6d32196df7dc2b9aeb0d76',
    messagingSenderId: '956367172035',
    projectId: 'proyecto2-700a3',
    authDomain: 'proyecto2-700a3.firebaseapp.com',
    storageBucket: 'proyecto2-700a3.appspot.com',
    measurementId: 'G-DC0MYLRCXN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9qSqgqXRXYCN7m5axT8Krww2dD27MU6I',
    appId: '1:956367172035:android:23f22565bfbc6ca2eb0d76',
    messagingSenderId: '956367172035',
    projectId: 'proyecto2-700a3',
    storageBucket: 'proyecto2-700a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5jcS65-Jg8fGO8M-PtGcmzjBqgJLbd-w',
    appId: '1:956367172035:ios:3110ad39961ebd7deb0d76',
    messagingSenderId: '956367172035',
    projectId: 'proyecto2-700a3',
    storageBucket: 'proyecto2-700a3.appspot.com',
    iosBundleId: 'com.example.proyecto2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5jcS65-Jg8fGO8M-PtGcmzjBqgJLbd-w',
    appId: '1:956367172035:ios:3110ad39961ebd7deb0d76',
    messagingSenderId: '956367172035',
    projectId: 'proyecto2-700a3',
    storageBucket: 'proyecto2-700a3.appspot.com',
    iosBundleId: 'com.example.proyecto2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbCmt8p5zBZYP5SoDd8uBO7GcEFSu19Ik',
    appId: '1:956367172035:web:d569e47d7a6d6949eb0d76',
    messagingSenderId: '956367172035',
    projectId: 'proyecto2-700a3',
    authDomain: 'proyecto2-700a3.firebaseapp.com',
    storageBucket: 'proyecto2-700a3.appspot.com',
    measurementId: 'G-QBYTYTWB8Y',
  );
}
